(ns jdbc-client-portable.ui
  (:import (com.googlecode.lanterna SGR TerminalPosition TextColor$ANSI)
           (com.googlecode.lanterna.terminal DefaultTerminalFactory Terminal)))

(defn one []
  (let [terminal-factory (DefaultTerminalFactory.)
        terminal (doto (.createTerminal terminal-factory)
                   (.putCharacter \h)
                   (.putCharacter \e)
                   (.putCharacter \l)
                   (.putCharacter \l)
                   (.putCharacter \o)
                   (.putCharacter \!)
                   (.putCharacter \newline)
                   (.flush))]
    (Thread/sleep 2000)
    (let [start-position (.getCursorPosition terminal)]
      (.setCursorPosition terminal (-> start-position
                                       (.withRelativeColumn 3)
                                       (.withRelativeRow 1)))
      (.flush terminal)
      (Thread/sleep 2000)
      (.setBackgroundColor terminal (TextColor$ANSI/BLUE))
      (.setForegroundColor terminal (TextColor$ANSI/YELLOW))
      (.putCharacter terminal \h)
      (.putCharacter terminal \e)
      (.putCharacter terminal \l)
      (.putCharacter terminal \l)
      (.putCharacter terminal \o)
      (.putCharacter terminal \space )
      (.putCharacter terminal \o)
      (.putCharacter terminal \n)
      (.putCharacter terminal \space )
      (.putCharacter terminal \t)
      (.putCharacter terminal \h)
      (.putCharacter terminal \e)
      (.putCharacter terminal \space )
      (.putCharacter terminal \b)
      (.putCharacter terminal \l)
      (.putCharacter terminal \u)
      (.putCharacter terminal \e)
      (.flush terminal)
      (Thread/sleep 2000)

      (.setCursorPosition terminal (-> start-position
                                       (.withRelativeColumn 3)
                                       (.withRelativeRow 2)))
      (.flush terminal)
      (Thread/sleep 2000)
      (.enableSGR terminal (SGR/BOLD))
            (.putCharacter terminal \h)
      (.putCharacter terminal \e)
      (.putCharacter terminal \l)
      (.putCharacter terminal \l)
      (.putCharacter terminal \o)
      (.putCharacter terminal \space )
      (.putCharacter terminal \o)
      (.putCharacter terminal \n)
      (.putCharacter terminal \space )
      (.putCharacter terminal \t)
      (.putCharacter terminal \h)
      (.putCharacter terminal \e)
      (.putCharacter terminal \space )
      (.putCharacter terminal \b)
      (.putCharacter terminal \l)
      (.putCharacter terminal \u)
      (.putCharacter terminal \e)
      (.flush terminal)
      (Thread/sleep 2000)

      (.resetColorAndSGR terminal)
      (.setCursorPosition terminal (-> terminal
                                       (.getCursorPosition)
                                       (.withColumn 0)
                                       (.withRelativeRow 1)))
      (.putCharacter terminal \D)
      (.putCharacter terminal \o)
      (.putCharacter terminal \n)
      (.putCharacter terminal \e)
      (.putCharacter terminal \newline)
      (.flush terminal)      
      (Thread/sleep 2000)

      (.bell terminal)
      (.flush terminal)
      (Thread/sleep 2000)
      
      ))

  (System/exit 1))
